/* Generated By:JavaCC: Do not edit this line. parserBSConstants.java */
package behaviourComposition.parser.behaviour;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
@SuppressWarnings("all")
public interface parserBSConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIG = 5;
  /** RegularExpression Id. */
  int LABEL = 6;
  /** RegularExpression Id. */
  int LEGAL = 7;
  /** RegularExpression Id. */
  int IN = 8;
  /** RegularExpression Id. */
  int FIN = 9;
  /** RegularExpression Id. */
  int IDENTIFIER = 10;
  /** RegularExpression Id. */
  int ARW = 11;
  /** RegularExpression Id. */
  int PGA = 12;
  /** RegularExpression Id. */
  int PGC = 13;
  /** RegularExpression Id. */
  int PQA = 14;
  /** RegularExpression Id. */
  int PQC = 15;
  /** RegularExpression Id. */
  int EQ = 16;
  /** RegularExpression Id. */
  int VR = 17;
  /** RegularExpression Id. */
  int VGT = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<DIG>",
    "<LABEL>",
    "<LEGAL>",
    "<IN>",
    "<FIN>",
    "<IDENTIFIER>",
    "<ARW>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\",\"",
    "\"\\\"\"",
  };

}
