/* Generated By:JavaCC: Do not edit this line. parserTSConstants.java */
package behaviourComposition.parser.transitionSystem;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
@SuppressWarnings("all")
public interface parserTSConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIG = 5;
  /** RegularExpression Id. */
  int LABEL = 6;
  /** RegularExpression Id. */
  int IN = 7;
  /** RegularExpression Id. */
  int IDENTIFIER = 8;
  /** RegularExpression Id. */
  int ARW = 9;
  /** RegularExpression Id. */
  int PGA = 10;
  /** RegularExpression Id. */
  int PGC = 11;
  /** RegularExpression Id. */
  int PQA = 12;
  /** RegularExpression Id. */
  int PQC = 13;
  /** RegularExpression Id. */
  int EQ = 14;
  /** RegularExpression Id. */
  int VR = 15;
  /** RegularExpression Id. */
  int VGT = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<DIG>",
    "<LABEL>",
    "<IN>",
    "<IDENTIFIER>",
    "<ARW>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\",\"",
    "\"\\\"\"",
  };

}
